### ISSUE TITLE
River rendering causes excessive lag

### ISSUE THREAD

**Issue by MoroBagg** [moltenwolfcub/Forest-Game#3] opened 2023-07-18 11:17 UTC
**Describe the bug**
Over time, if you play for a while the fps drops drastically and the time goes by slower turning the game into a choppy mess. 

**To Reproduce**
1. Wait a while
2. Time will seem to slow down and fps will drop drastically

**Expected behavior**
Time and fps should be flowing at an equal speed no matter on where you are in the game.

**Your Environment (please complete the following information):**
 - OS: windows
 - Architecture: x86_64
 - Version 0.03

**Extra info**
This is all that I am aware of, the bug probably does extend further and affect more. This should be recreated and inspected further just in case it is something game breaking.

**Comment by moltenwolfcub** [comment] 2023-07-19 19:50
As far as I can tell currently, I think it's something related to memory being held onto after it needs to be. The most likely culprit is the lineart system; it probably is not properly getting rid of the images used to draw the lines.

I will have a look into this shortly. Currently working on some new features though.

**Comment by moltenwolfcub** [comment] 2023-08-31 09:46
I can't seem to recreate this issue on my computer. Can you confirm that it still exists on the latest release of the game (0.1.0)

**Comment by moltenwolfcub** [comment] 2023-09-27 20:33
Release 0.1.1 has just came out and has optimised lineart a lot with caches so the issue might have been fixed. I can't reproduce so can't confirm. Please test it out.

**Comment by MoroBagg** [comment] 2023-09-28 19:27
yeah it may just have been the lineart, although I'm still finding it quite laggy despite the recent changes. Yes this is on 0.1.1 if you were wondering.

**Comment by moltenwolfcub** [comment] 2023-10-05 09:13
After some testing on a lower power machine, I've managed to reproduce this bug and I've found that the laggy behaviour only occurs while the river is on the screen (because of off-screen culling) meaning the lag comes from something in the river's render code. I will have a look into it and maybe try running a profiler.

**Comment by moltenwolfcub** [comment] 2023-10-07 18:47
I think I've found the issue in the code. The river rendering was calling the `ApplyLineart` function every render cycle because the cache wasn't properly being used. (Stupidity of leaving the `markDirty` call in the cache assignment method from testing). This should fix the issue in an upcoming pr. Just need to wrap up a few more commits then it'll be merged

**Closed as completed** 2023-10-07 20:23 UTC
Labels: bug, performance

**Comment by moltenwolfcub** [comment] 2023-10-07 20:25
This(#4) should have fixed the issue. According to profiler and my intuition, the bug should have been fixed however I don't currently have a lower power machine to test on so I can't entirely confirm it's completion.

If it's still a problem, re-open the issue and I'll have a further look.

**Comment by moltenwolfcub** [comment] 2023-10-07 20:27
This PR has been merged and will be included the next release (probably 0.2.0 unless there's a necessity for a 0.1.2)

**Comment by moltenwolfcub** [comment] 2023-10-31 20:56
This [recent patch](https://github.com/moltenwolfcub/Forest-Game/releases/tag/v0.1.1-PumpkinPatch) unofficially includes the fix for this bug in it (it will be official in the next main release.)

I would appreciate if you could confirm that the issue has been fixed by the pr(#4).

**Comment by MoroBagg** [comment] 2023-11-07 11:26
Yeah thank, in the pr fixed it pr(#4) . The issue is no longer there.
